# This is a build file for Travis CI.
# See: https://travis-ci.org/mbitsnbites/buildcache

language: cpp

matrix:
  include:
    # Linux GCC
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build
      script:
        - mkdir out && cd out
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src
        - cmake --build .
        - CTEST_OUTPUT_ON_FAILURE=TRUE ctest
        - ../test_scripts/run_lock_file_stresstest.sh
        - ../test_scripts/build_with_buildcache.sh

    # macOS clang
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - ninja
          update: true
      script:
        - mkdir out && cd out
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src
        - cmake --build .
        - CTEST_OUTPUT_ON_FAILURE=TRUE ctest
        - ../test_scripts/run_lock_file_stresstest.sh
        - ../test_scripts/build_with_buildcache.sh

    # Windows MinGW cross compile on Linux
    - os: linux
      dist: xenial
      compiler: mingw
      addons:
        apt:
          packages:
            - ninja-build
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
      script:
        - mkdir out && cd out
        - CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_WITH_INSTALL_RPATH=on ../src
        - cmake --build .

    # Windows MSVC 2017
    - os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="CC=cl.exe && CXX=cl.exe"
      before_install:
        - eval "${MATRIX_EVAL}"
      install:
        - choco install ninja
      script:
        - mkdir out && cd out
        - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&'
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../src '&&'
          ninja
        - CTEST_OUTPUT_ON_FAILURE=TRUE ninja test
        - ../test_scripts/run_lock_file_stresstest.sh
        # TODO(m): It would be nice to get this working...
        #- cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && "C:\Program Files\Git\bin\sh.exe" ../test_scripts/build_with_buildcache.sh'
