#define BUILDCACHE_VERSION_MAJOR 0
#define BUILDCACHE_VERSION_MINOR 28
#define BUILDCACHE_VERSION_PATCH 0
#define BUILDCACHE_VERSION_STRING "0.28.0"

#define BUILDCACHE_COPYRIGHT_STRING "Copyright (c) 2018-2022 Marcus Geelnard"

